In [36]:
import numpy as np

In [37]:
phi1 = np.array([[3],[2]])
phi2 = np.array([[1],[1]])
phi3 = np.array([[4],[-6]])
phi4 = np.array([[2],[1]])
phi = (phi1, phi2, phi3, phi4)

y1, y2, y3, y4 = 6, 1, -3, 4
y = (y1, y2, y3, y4)

In [38]:
P_inv = 0
B = 0
for _phi in phi:
    P_inv += _phi@np.transpose(_phi)
for _y, _phi in zip(y, phi):
    B += _y*_phi

P = np.linalg.inv(P_inv)
theta = P@B
theta

array([[1.11594203],
       [1.23188406]])

In [39]:
# new data
phi5 = np.array([[2], [2]])
y5 = 3
P_tprev = P
theta_tprev = theta

In [40]:
#calculate new theta using batch method
y = (y1, y2, y3, y4, y5)
phi = (phi1, phi2, phi3, phi4, phi5)
P_inv = 0
B = 0
for _phi in phi:
    P_inv += _phi@np.transpose(_phi)
for _y, _phi in zip(y, phi):
    B += _y*_phi

P = np.linalg.inv(P_inv)
theta_t = P@B
theta_t

array([[0.98198198],
       [1.12612613]])

In [41]:
# calculate new Pt from previous P(t-1) and new data
P_t = P_tprev - (P_tprev@phi5@np.transpose(phi5)@P_tprev)/(1+np.transpose(phi5)@P_tprev@phi5)
theta_t = theta_tprev + (P_tprev@phi5)/(1+np.transpose(phi5)@P_tprev@phi5)*(y5-np.transpose(phi5)@theta_tprev)

In [42]:
theta_t

array([[0.98198198],
       [1.12612613]])